//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pupil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pupil()
        {
            this.transgress_pupil = new HashSet<transgress_pupil>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime birthday { get; set; }
        public int class_id { get; set; }
        public string type { get; set; }
        public double point { get; set; }
        public string note { get; set; }
    
        public virtual theclass theclass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transgress_pupil> transgress_pupil { get; set; }
    }
}
